### PR TITLE
fix: fixed missing env var in postgres and minor readme changes

### PR DESCRIPTION
**Pull request by Ryuk-me**

### CODE REVIEW

**Review by saikishorr — COMMENTED** [review]
the code of Readme.md and docker-compose.yml and good and nice,but the the test.py file is empty

**Comment by Ryuk-me** [comment]
@Saikishor164 Thank you for reviewing and I am giving it a finishing touch having some issue with Postgres on docker, trying to fix it and will also update the testcases.

**Comment by Ryuk-me** [comment]
@Saikishor164 I have added testcase and fixed docker issue, please review it once you're available.

**Comment by Ryuk-me** [comment]
@Saikishor164 I hope you are doing good.
Quick question are you from waterdip? 😅

**Review by saikishorr — COMMENTED** [review]
👍

**Pull request merged**
